services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: "card-project"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 098098
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data/postgers-data:/var/lib/postgresql/pgdata
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.11
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=jaskier
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./data/rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672

  card-project-api:
    container_name: card-project
    image: card-project
    environment:
      - DB_Host     = "localhost"
      - DB_Port     = "5432"
      - DB_User     = "postgres"
      - DB_Password = "098098"
      - DB_Name   = "CardProject"
      - PORT_ServerPort = "8080"
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  migrate:
      container_name: migrater
      image: migrate/migrate
      depends_on:
        - postgres
      volumes:
        - C:\my\go\card-project\migrations:/database
      command:
        [ "-path", "/database", "-database",  "postgres://postgres:098098@postgres:5432/card-project?sslmode=disable", "up" ]

volumes:
  postgers-data:
  pgadmin-data:
